### ISSUE TITLE
High memory consumption if the target server is down

### ISSUE THREAD

**Issue by tiagoalves** [bpaquet/node-logstash#103]
We're using node-logstash (thanks for the great project, btw) to send data to a Graylog instance. If the Graylog server is down or a DNS error occurs, for instance, the node-logstash process's memory starts to grow until there's no more memory available.

It appears that this problem can be avoided using ZeroMQ and the back pressure settings. Is there a way to discard new messages or pause the log using the Gelf output?

Thank you.

**Comment by bpaquet** [comment]
Do you mean to implement the back pressure mechanism to Gelf Output plugin ?

**Comment by tiagoalves** [comment]
Yes, that's what I meant.

**Comment by bpaquet** [comment]
The problem is not detect a problem. It's about to detect the server is back online.
This is handled in ZMQ at ZMQ level. With Gelf, the plugin can not know when the server is back on line.
Solution :
- an url to be monitored
- keep a message in error, and try to resend it every 5s
- reactivate inputs every 5sec (bad idea, lot of messages will be lost).
What do you think ?

Do you need to store messages in error to resend them when server is back on line ?

**Comment by tiagoalves** [comment]
I see. I agree with your first two points (have a way to monitor Graylog server state and an retry to send the messages every few seconds).

What I was expecting is that while Graylog is down, node-logstash would cache messages up to a certain configurable number or by cache size (in kb). If the maximum number of messages or cache size is reached, newer messages would simply be discarded. Personally, I could live with that but I don't know if that's what you expect and if it's the standard practice.

**Comment by bpaquet** [comment]
Which transport do you use to graylog ? Gelf with output gelf node-logstash plugin ?

**Comment by tiagoalves** [comment]
Yes, I use the Gelf output plugin: `output://gelf://host:port`

**Comment by bpaquet** [comment]
So, this plugin use UDP transport. Even if the destination is not
reachable, there are no impact on node-logstash :)

What do you mean by dns error ?
